import { User, Report, DashboardStats, Subscription, SupportTicket, Match, AuditLog, PromoCode } from '@/types';

// Dashboard Stats
export const mockDashboardStats: DashboardStats = {
    totalUsers: 125482,
    activeUsers: 89234,
    newUsersToday: 342,
    newUsersThisWeek: 2156,
    newUsersThisMonth: 8942,
    premiumUsers: 12482,
    totalMatches: 456789,
    totalMessages: 2345678,
    pendingReports: 84,
    pendingVerifications: 156,
    mrr: 124500,
    arr: 1494000,
    churnRate: 2.4,
    conversionRate: 8.5,
};

// Mock Users
export const mockUsers: User[] = [
    {
        id: 'user-1',
        name: 'Can Demir',
        email: 'can.demir@email.com',
        phone: '+90 532 123 4567',
        age: 28,
        gender: 'male',
        location: { city: 'İstanbul', country: 'Türkiye' },
        photos: ['https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400'],
        bio: 'Yazılım mühendisi, kitap kurdu',
        interests: ['Kitap', 'Yazılım', 'Kahve', 'Seyahat'],
        status: 'active',
        isPremium: true,
        premiumTier: 'gold',
        premiumExpiry: new Date('2024-12-31'),
        isVerified: true,
        reportCount: 0,
        matchCount: 45,
        messageCount: 234,
        lastActive: new Date(),
        createdAt: new Date('2023-06-15'),
        updatedAt: new Date(),
    },
    {
        id: 'user-2',
        name: 'Selin Kaya',
        email: 'selin.kaya@email.com',
        phone: '+90 533 234 5678',
        age: 26,
        gender: 'female',
        location: { city: 'Ankara', country: 'Türkiye' },
        photos: ['https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400'],
        bio: 'Fotoğrafçı, doğa aşığı',
        interests: ['Fotoğrafçılık', 'Doğa', 'Yoga'],
        status: 'active',
        isPremium: false,
        isVerified: true,
        reportCount: 3,
        matchCount: 28,
        messageCount: 156,
        lastActive: new Date(Date.now() - 3600000),
        createdAt: new Date('2023-08-20'),
        updatedAt: new Date(),
    },
    {
        id: 'user-3',
        name: 'Mert Yılmaz',
        email: 'mert.yilmaz@email.com',
        age: 31,
        gender: 'male',
        location: { city: 'İzmir', country: 'Türkiye' },
        photos: ['https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400'],
        bio: 'Müzisyen',
        status: 'banned',
        isPremium: false,
        isVerified: false,
        reportCount: 12,
        matchCount: 5,
        messageCount: 89,
        lastActive: new Date(Date.now() - 86400000 * 7),
        createdAt: new Date('2023-04-10'),
        updatedAt: new Date(),
    },
    {
        id: 'user-4',
        name: 'Elif Arslan',
        email: 'elif.arslan@email.com',
        age: 24,
        gender: 'female',
        location: { city: 'İstanbul', country: 'Türkiye' },
        photos: ['https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400'],
        bio: 'Grafik tasarımcı',
        status: 'pending',
        isPremium: true,
        premiumTier: 'platinum',
        isVerified: false,
        reportCount: 0,
        matchCount: 12,
        messageCount: 45,
        lastActive: new Date(Date.now() - 1800000),
        createdAt: new Date('2024-01-05'),
        updatedAt: new Date(),
    },
    {
        id: 'user-5',
        name: 'Ahmet Özkan',
        email: 'ahmet.ozkan@email.com',
        age: 35,
        gender: 'male',
        location: { city: 'Bursa', country: 'Türkiye' },
        photos: ['https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400'],
        bio: 'İşletme sahibi',
        status: 'active',
        isPremium: true,
        premiumTier: 'basic',
        isVerified: true,
        reportCount: 1,
        matchCount: 67,
        messageCount: 489,
        lastActive: new Date(),
        createdAt: new Date('2022-11-20'),
        updatedAt: new Date(),
    },
];

// Mock Reports
export const mockReports: Report[] = [
    {
        id: 'report-1',
        reporterId: 'user-2',
        reporterName: 'Selin Kaya',
        reportedUserId: 'user-3',
        reportedUserName: 'Mert Yılmaz',
        collection: 'reports',
        type: 'user',
        reason: 'harassment',
        reasonDisplayName: 'Taciz',
        description: 'Uygunsuz ve rahatsız edici mesajlar gönderiyor.',
        status: 'pending',
        priority: 'high',
        createdAt: new Date(Date.now() - 7200000),
        updatedAt: new Date(),
    },
    {
        id: 'report-2',
        reporterId: 'user-1',
        reporterName: 'Can Demir',
        reportedUserId: 'user-6',
        reportedUserName: 'Fake Account',
        collection: 'reports',
        type: 'user',
        reason: 'fake_profile',
        reasonDisplayName: 'Sahte Profil',
        description: 'Profil fotoğrafları başka birine ait.',
        status: 'pending',
        priority: 'medium',
        createdAt: new Date(Date.now() - 86400000),
        updatedAt: new Date(),
    },
    {
        id: 'report-3',
        reporterId: 'user-4',
        reporterName: 'Elif Arslan',
        reportedUserId: 'user-7',
        reportedUserName: 'Spam User',
        collection: 'reports',
        type: 'user',
        reason: 'spam',
        reasonDisplayName: 'Spam',
        description: 'Reklam linkleri paylaşıyor.',
        status: 'reviewed',
        priority: 'low',
        resolution: 'Kullanıcıya uyarı gönderildi.',
        createdAt: new Date(Date.now() - 172800000),
        updatedAt: new Date(),
        resolvedAt: new Date(),
    },
    {
        id: 'report-4',
        reporterId: 'user-5',
        reporterName: 'Ahmet Özkan',
        reportedUserId: 'user-8',
        reportedUserName: 'Scammer',
        collection: 'reports',
        type: 'user',
        reason: 'scam',
        reasonDisplayName: 'Dolandırıcılık',
        description: 'Para transferi istedi.',
        status: 'pending',
        priority: 'critical',
        createdAt: new Date(Date.now() - 3600000),
        updatedAt: new Date(),
    },
];

// Mock Subscriptions
export const mockSubscriptions: Subscription[] = [
    {
        id: 'sub-1',
        userId: 'user-1',
        userName: 'Can Demir',
        plan: 'yearly',
        tier: 'gold',
        amount: 1199,
        currency: 'TRY',
        status: 'active',
        startDate: new Date('2024-01-01'),
        endDate: new Date('2024-12-31'),
        autoRenew: true,
        paymentMethod: 'Kredi Kartı',
    },
    {
        id: 'sub-2',
        userId: 'user-4',
        userName: 'Elif Arslan',
        plan: 'monthly',
        tier: 'platinum',
        amount: 199,
        currency: 'TRY',
        status: 'active',
        startDate: new Date('2024-01-15'),
        endDate: new Date('2024-02-15'),
        autoRenew: true,
        paymentMethod: 'Google Pay',
    },
    {
        id: 'sub-3',
        userId: 'user-5',
        userName: 'Ahmet Özkan',
        plan: 'quarterly',
        tier: 'basic',
        amount: 449,
        currency: 'TRY',
        status: 'cancelled',
        startDate: new Date('2023-10-01'),
        endDate: new Date('2024-01-01'),
        autoRenew: false,
        paymentMethod: 'Kredi Kartı',
    },
];

// Mock Audit Logs
export const mockAuditLogs: AuditLog[] = [
    {
        id: 'log-1',
        adminId: 'admin-1',
        adminName: 'Admin User',
        action: 'user_banned',
        targetType: 'user',
        targetId: 'user-3',
        details: 'Mert Yılmaz kullanıcısı yasaklandı. Sebep: Çoklu taciz raporu.',
        ipAddress: '185.122.45.10',
        location: 'İstanbul, TR',
        createdAt: new Date(Date.now() - 1800000),
    },
    {
        id: 'log-2',
        adminId: 'admin-2',
        adminName: 'Moderator',
        action: 'report_resolved',
        targetType: 'report',
        targetId: 'report-3',
        details: 'Spam raporu çözüldü. Kullanıcıya uyarı gönderildi.',
        ipAddress: '78.45.123.67',
        location: 'Ankara, TR',
        createdAt: new Date(Date.now() - 7200000),
    },
    {
        id: 'log-3',
        adminId: 'admin-1',
        adminName: 'Admin User',
        action: 'user_verified',
        targetType: 'user',
        targetId: 'user-1',
        details: 'Can Demir kullanıcısı doğrulandı.',
        ipAddress: '185.122.45.10',
        location: 'İstanbul, TR',
        createdAt: new Date(Date.now() - 86400000),
    },
];

// Mock Support Tickets
export const mockTickets: SupportTicket[] = [
    {
        id: 'ticket-1',
        userId: 'user-1',
        userName: 'Can Demir',
        userEmail: 'can.demir@email.com',
        isPremium: true,
        subject: 'Ödeme ekranında hata alıyorum',
        category: 'billing',
        priority: 'high',
        status: 'open',
        messages: [
            {
                id: 'msg-1',
                senderId: 'user-1',
                senderName: 'Can Demir',
                senderType: 'user',
                content: 'Ödeme ekranında sürekli "hata kodu 500" alıyorum, üyeliğimi yenileyemiyorum. Yardım lütfen!',
                createdAt: new Date(Date.now() - 120000),
            },
        ],
        createdAt: new Date(Date.now() - 120000),
        updatedAt: new Date(),
    },
    {
        id: 'ticket-2',
        userId: 'user-2',
        userName: 'Selin Kaya',
        userEmail: 'selin.kaya@email.com',
        isPremium: false,
        subject: 'Hesabıma giriş yapamıyorum',
        category: 'account',
        priority: 'medium',
        status: 'in_progress',
        assignedTo: 'admin-1',
        messages: [
            {
                id: 'msg-2',
                senderId: 'user-2',
                senderName: 'Selin Kaya',
                senderType: 'user',
                content: 'Şifremi sıfırlamayı denedim ama email gelmiyor.',
                createdAt: new Date(Date.now() - 3600000),
            },
            {
                id: 'msg-3',
                senderId: 'admin-1',
                senderName: 'Admin User',
                senderType: 'admin',
                content: 'Merhaba Selin Hanım, hesabınızı kontrol ediyorum. Lütfen bekleyin.',
                createdAt: new Date(Date.now() - 1800000),
            },
        ],
        createdAt: new Date(Date.now() - 3600000),
        updatedAt: new Date(),
    },
];

// Chart Data
export const mockUserGrowthData = [
    { date: '2024-01-01', value: 115000 },
    { date: '2024-01-08', value: 117500 },
    { date: '2024-01-15', value: 119200 },
    { date: '2024-01-22', value: 121800 },
    { date: '2024-01-29', value: 123400 },
    { date: '2024-02-05', value: 125482 },
];

export const mockRevenueData = [
    { date: '2024-01-01', value: 98000 },
    { date: '2024-01-08', value: 105000 },
    { date: '2024-01-15', value: 112000 },
    { date: '2024-01-22', value: 118000 },
    { date: '2024-01-29', value: 121000 },
    { date: '2024-02-05', value: 124500 },
];

export const mockGenderDistribution = {
    male: 52,
    female: 46,
    other: 2,
};

export const mockAgeDistribution = {
    '18-24': 28,
    '25-34': 42,
    '35-44': 18,
    '45-54': 8,
    '55+': 4,
};
